/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every published API version */
        get: operations["listVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index of the v1 resources */
        get: operations["v1Index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How current the stored data is
         * @description Cheap enough to poll. When `meta.dataVersion` is unchanged since the last
         *     call, nothing else needs refetching.
         */
        get: operations["v1Meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document */
        get: operations["v1OpenApiJson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document, as YAML */
        get: operations["v1OpenApiYaml"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List imported events, newest first
         * @description Only events that have participants. An event without a single standing
         *     carries no result and is left out of every response.
         */
        get: operations["v1ListEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One event with standings, sets and character usage
         * @description The raw material every ranking is built from, so a client can compute
         *     figures of its own. `sets` comes in bracket order and carries the round,
         *     the score and the characters of both sides, which is enough to redraw
         *     the bracket. An event without participants is reported as `404`, the
         *     same as an unknown id.
         */
        get: operations["v1GetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog of the ranking tables and their rules */
        get: operations["v1ListRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rankings/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One ranking table */
        get: operations["v1GetRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every player that ever entered an imported event
         * @description A roster, not a ranking: no attendance threshold and no malus.
         *     `averagePlacement` is the overall average across all imported events.
         */
        get: operations["v1ListPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One player's placements, head-to-head record and characters */
        get: operations["v1GetPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ranked-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slippi's Free Ranked Day window
         * @description Computed from a fixed cadence, not fetched from Slippi. The `schedule`
         *     block is enough to keep counting down offline. Not conditionally
         *     cacheable — `secondsRemaining` moves with the clock.
         */
        get: operations["v1RankedDay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Meta: {
            /** @example v1 */
            apiVersion?: string | null;
            /**
             * Format: date-time
             * @description When the newest imported row was written.
             */
            dataUpdatedAt?: string | null;
            /** @description Fingerprint of the served data; unchanged means nothing moved. */
            dataVersion?: string;
        };
        Pagination: {
            limit?: number;
            offset?: number;
            total?: number;
            hasMore?: boolean;
        };
        /** @description RFC 9457 problem detail. */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        VersionInfo: {
            /** @example v1 */
            version?: string;
            /** @enum {string} */
            status?: "preview" | "stable" | "deprecated";
            /** @example /api/v1 */
            basePath?: string;
            documentation?: string;
            /** Format: date */
            releasedOn?: string;
            /** Format: date */
            deprecatedOn?: string | null;
            /** Format: date */
            sunsetOn?: string | null;
            successor?: string | null;
        };
        ImportRun: {
            /** @enum {string} */
            status?: "queued" | "running" | "completed" | "failed";
            /** @enum {string} */
            mode?: "full" | "incremental";
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
        };
        EventSummary: {
            /** @description start.gg event id */
            eventId?: number;
            name?: string;
            slug?: string | null;
            /** @description Tournament and event name combined. */
            label?: string;
            /** Format: date-time */
            startAt?: string | null;
            numEntrants?: number | null;
            tournament?: {
                name?: string;
                slug?: string | null;
            };
            /** Format: uri */
            startggUrl?: string | null;
        };
        EventDetail: components["schemas"]["EventSummary"] & {
            standings?: components["schemas"]["Standing"][];
            sets?: components["schemas"]["Set"][];
            characters?: components["schemas"]["EventCharacterUsage"][];
        };
        Standing: {
            playerId?: string;
            displayName?: string;
            /** @description The absolute start.gg placement. */
            placement?: number;
            /**
             * @description The placement re-ranked among the stored players (standard
             *     competition ranking) — what the ranking average uses.
             */
            rankPlacement?: number;
        };
        /**
         * @description One completed set, in the bracket order start.gg played them. Only sets
         *     between stored players are kept. Sets imported before the bracket
         *     context was collected report `round`, `roundText`, `phase` and the
         *     scores as `null` and carry no `characters`.
         */
        Set: {
            /** @description Stable id of the set within this API. */
            setId?: number;
            winnerPlayerId?: string;
            loserPlayerId?: string;
            winnerName?: string;
            loserName?: string;
            /** @description start.gg bracket round — positive in winners, negative in losers. */
            round?: number | null;
            /** @description The spelled-out round, e.g. "Winners Quarter-Final". */
            roundText?: string | null;
            /** @description The phase the set was played in. */
            phase?: string | null;
            /** @description Games won. Null when start.gg reports no score, e.g. a DQ. */
            winnerScore?: number | null;
            loserScore?: number | null;
            /** @description start.gg's own rendering of the result, the fallback when there is no score. */
            displayScore?: string | null;
            /** @description What both sides picked in this set. */
            characters?: components["schemas"]["SetCharacterPick"][];
        };
        SetCharacterPick: {
            playerId?: string;
            characterId?: number;
            characterName?: string;
            /** @description Games of the set this character was picked in. */
            games?: number;
        };
        EventCharacterUsage: {
            playerId?: string;
            characterId?: number;
            characterName?: string;
            count?: number;
        };
        Character: {
            characterId?: number;
            characterName?: string;
            count?: number;
            /** Format: float */
            percentage?: number;
        };
        RankingDescriptor: {
            /** @enum {string} */
            type?: "quarterly" | "power";
            label?: string;
            path?: string;
            /** @enum {string} */
            periodType?: "quarter" | "half-year";
            scopes?: {
                /** @enum {string} */
                scope?: "qualified" | "all";
                label?: string;
                minimumEntrants?: number | null;
            }[];
            rules?: {
                minimumAttendances?: number;
                /** Format: float */
                nonAttendancePenalty?: number;
            };
        };
        RankingTable: {
            /** @enum {string} */
            type?: "quarterly" | "power";
            /** @enum {string} */
            scope?: "qualified" | "all";
            label?: string;
            scopeLabel?: string;
            /** @enum {string} */
            periodType?: "quarter" | "half-year";
            rules?: {
                minimumEntrants?: number | null;
                minimumAttendances?: number;
                /** Format: float */
                nonAttendancePenalty?: number;
            };
            overall?: components["schemas"]["RankingSection"];
            periods?: components["schemas"]["RankingPeriod"][];
        };
        RankingSection: {
            eventsConsidered?: number;
            rows?: components["schemas"]["RankingRow"][];
        };
        RankingPeriod: {
            /**
             * @example 2026-Q3
             * @example 2026-H1
             */
            key?: string;
            /**
             * @example Q3 2026
             * @example 1. Halbjahr 2026
             */
            label?: string;
        } & components["schemas"]["RankingSection"];
        RankingRow: {
            rank?: number;
            playerId?: string;
            displayName?: string;
            attendances?: number;
            /**
             * Format: float
             * @description Average rank placement, including the malus where one applies.
             */
            averagePlacement?: number;
            topCharacter?: components["schemas"]["Character"] | null;
        };
        PlayerSummary: {
            /** @example player:12345 */
            playerId?: string;
            displayName?: string;
            attendances?: number;
            /** Format: float */
            averagePlacement?: number;
            topCharacter?: components["schemas"]["Character"] | null;
        };
        PlayerDetail: {
            playerId?: string;
            displayName?: string;
            attendances?: number;
            /** Format: float */
            averagePlacement?: number;
            bestPlacement?: number;
            /** @description Oldest first. */
            placements?: {
                eventId?: number;
                eventName?: string;
                tournamentName?: string;
                label?: string;
                /** Format: date-time */
                startAt?: string | null;
                numEntrants?: number | null;
                /** @description The absolute start.gg placement. */
                placement?: number;
            }[];
            headToHead?: {
                summary?: {
                    wins?: number;
                    losses?: number;
                };
                opponents?: {
                    playerId?: string;
                    displayName?: string;
                    wins?: number;
                    losses?: number;
                    totalSets?: number;
                    /** Format: float */
                    winRate?: number;
                }[];
            };
            characters?: {
                totalSelections?: number;
                top?: components["schemas"]["Character"][];
            };
        };
        RankedDay: {
            /** @description Whether a window is running right now. */
            active?: boolean;
            /** @description Stable id of the window the payload describes. */
            windowId?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** @description Until the running window ends, or until the next one starts. */
            secondsRemaining?: number;
            schedule?: {
                /** Format: date-time */
                anchor?: string;
                cycleDays?: number;
                durationHours?: number;
            };
        };
    };
    responses: {
        /** @description The cached copy is still current. No body. */
        NotModified: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description A query parameter was not understood. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The data store is temporarily unreachable — retry later. */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description The ETag of a cached copy. A match is answered with 304. */
        IfNoneMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Weak validator; send it back as If-None-Match. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listVersions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @example v1 */
                            current: string;
                            versions: components["schemas"]["VersionInfo"][];
                        };
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    v1Index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource paths and the version's status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            version?: string;
                            status?: string;
                            documentation?: string;
                            resources?: {
                                [key: string]: string;
                            };
                        };
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    v1Meta: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Counts and the last import. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            eventCount?: number;
                            playerCount?: number;
                            lastImport?: components["schemas"]["ImportRun"] | null;
                        };
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1OpenApiJson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI description as JSON (no data/meta envelope). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    v1OpenApiYaml: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The OpenAPI description as YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/yaml": string;
                };
            };
        };
    };
    v1ListEvents: {
        parameters: {
            query?: {
                /** @description Only events with at least this many entrants. */
                minEntrants?: number;
                limit?: number;
                offset?: number;
            };
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventSummary"][];
                        meta: components["schemas"]["Meta"] & {
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            304: components["responses"]["NotModified"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1GetEvent: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /** @description The start.gg event id. */
                eventId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["EventDetail"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1ListRankings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One descriptor per table. No ranking is computed for this. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RankingDescriptor"][];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
    v1GetRanking: {
        parameters: {
            query?: {
                /**
                 * @description `qualified` counts only events with at least 6 entrants, `all`
                 *     counts every imported event.
                 */
                scope?: "qualified" | "all";
                /** @description Return only this period, e.g. `2026-Q3` or `2026-H1`. */
                period?: string;
            };
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /**
                 * @description `quarterly` — the landing-page table: at least 2 attendances, no
                 *     non-attendance malus, broken down per quarter.
                 *     `power` — the power ranking: at least 3 attendances, +0.05 placement
                 *     points per missed event, broken down per half-year.
                 */
                type: "quarterly" | "power";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The table, overall plus per period. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RankingTable"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1ListPlayers: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on the display name. */
                q?: string;
                sort?: "name" | "average" | "attendances";
                limit?: number;
                offset?: number;
            };
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of players. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlayerSummary"][];
                        meta: components["schemas"]["Meta"] & {
                            pagination?: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
            304: components["responses"]["NotModified"];
            400: components["responses"]["BadRequest"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1GetPlayer: {
        parameters: {
            query?: never;
            header?: {
                /** @description The ETag of a cached copy. A match is answered with 304. */
                "If-None-Match"?: components["parameters"]["IfNoneMatch"];
            };
            path: {
                /** @description The prefixed start.gg identity, e.g. `player:12345`. */
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The player. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PlayerDetail"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
            304: components["responses"]["NotModified"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    v1RankedDay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The running window, or the next one when none is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["RankedDay"];
                        meta: components["schemas"]["Meta"];
                    };
                };
            };
        };
    };
}
